from turtle import *
import time
pensize(5)
pencolor("red")
fillcolor("pink")
hideturtle()
begin_fill()
left(135)
forward(100)
circle(-50,180)
left(90)
circle(-50,180)
forward(100)
end_fill()
penup()
goto(0,80)
pendown()
pencolor("yellow")
write("一颗心",align = "center",font = ("Arial",15,"bold"))
time.sleep(1)
penup()
goto(0,-200)
pendown()
pencolor("red")
write("吓你一跳",align = "center",font = ("Arial",150,"bold"))
time.sleep(1)